apiVersion: v1
home: https://docs.solo.io/web-assembly-hub/latest
icon: https://raw.githubusercontent.com/solo-io/wasme/master/docs/content/img/logo.png
name: Wasme Operator
sources:
- https://github.com/solo-io/wasme
version: vdev
