
wasmeOperator:
  image:
    pullPolicy: Always
    registry: quay.io/solo-io
    repository: wasme
    tag: dev
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
wasmeCache:
  image:
    pullPolicy: Always
    registry: quay.io/solo-io
    repository: wasme
    tag: dev
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
