steps:

  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p ./gopath/pkg && cd ./gopath/pkg && gsutil cat gs://$PROJECT_ID-cache/wasme/wasme-mod.tar.gz | tar -xzf -']
    id: 'untar-mod-cache'

  - name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
    args: ['generate-deps']
    env:
      - 'GO111MODULE=on'
      - 'TAGGED_VERSION=$TAG_NAME'
      - 'PROJECT_ROOT=github.com/solo-io/autopilot'
      - 'GOPATH=/workspace/gopath'
    secretEnv: ['GITHUB_TOKEN']
    id: 'install dependencies'

  - name: gcr.io/cloud-builders/gcloud
    args: ['container', 'clusters', 'get-credentials', 'wasme-ci-cluster', '--zone', 'us-central1-a']

  - name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
    env:
      - 'GO111MODULE=on'
      - 'TAGGED_VERSION=$TAG_NAME'
      - 'GOPATH=/workspace/gopath'
      - 'BUILD_ID=$BUILD_ID'
      - 'PROJECT_ROOT=github.com/solo-io/autopilot'
      - 'GOPATH=/workspace/gopath'
      - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-ci-cluster'
    args: ['-r', '-failFast', '-trace', '-progress']
    secretEnv: ['GITHUB_TOKEN']
    id: 'run-tests'

  - name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.0'
    args: ['build-images']
    env:
      - 'GO111MODULE=on'
      - 'TAGGED_VERSION=$TAG_NAME'
      - 'PROJECT_ROOT=github.com/solo-io/wasme'
      - 'GOPATH=/workspace/gopath'
    id: 'build-images'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD']
    secretEnv: ['QUAY_IO_PASSWORD']
    id: 'docker-login'

  - name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.0'
    args: ['publish-images', '-B']
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
      - 'TAGGED_VERSION=$TAG_NAME'
      - 'PROJECT_ROOT=github.com/solo-io/wasme'
      - 'GOPATH=/workspace/gopath'
    secretEnv: ['GITHUB_TOKEN']
    id: 'release-build-container'

  - name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.0'
    args: ['upload-github-release-assets', 'publish-docs', '-B']
    env:
      - 'GO111MODULE=on'
      - 'TAGGED_VERSION=$TAG_NAME'
      - 'PROJECT_ROOT=github.com/solo-io/wasme'
      - 'GOPATH=/workspace/gopath'
    secretEnv: ['GITHUB_TOKEN']
    id: 'release-assets-docs'

secrets:
  - kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
    secretEnv:
      GITHUB_TOKEN: CiQABlzmSYYiveU0gTxGH2139eaBUedjV3vNCxQmJU+nRPlfQ/YSUQCCPGSGzbGp49fwDYuefAx9V94b8mivdp9AqB7zQAa07VtGJmrGdg9ZuhKGFrrgqxwABE0LLVNHyngCSHYSYMH8Vn/mRtT7wQuEHBlKVGtqPw==
      QUAY_IO_PASSWORD: CiQABlzmSRx5TcOqbldXa/d/+bkmAfpNAWa3PTS06WvuloZL+vASaQCCPGSGCogonVZVEUNx4G3YJtWi18gSuNx4PvLe08q8xAflTMFkjsyQirAOK3Y2oCvgYwiw/ITcuydjkpMjxDygFyENXS9FKFJoAXHlPQE5qidKr8xxmxF5ezhmjGB0gjyjXIIkbSEnBg==

timeout: 1200s
tags: ['wasme']
options:
  machineType: 'N1_HIGHCPU_32'
