/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	wasmeiov1 "github.com/solo-io/wasme/pkg/operator/api/wasme.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFilterDeployments implements FilterDeploymentInterface
type FakeFilterDeployments struct {
	Fake *FakeWasmeV1
	ns   string
}

var filterdeploymentsResource = schema.GroupVersionResource{Group: "wasme.io", Version: "v1", Resource: "filterdeployments"}

var filterdeploymentsKind = schema.GroupVersionKind{Group: "wasme.io", Version: "v1", Kind: "FilterDeployment"}

// Get takes name of the filterDeployment, and returns the corresponding filterDeployment object, and an error if there is any.
func (c *FakeFilterDeployments) Get(name string, options v1.GetOptions) (result *wasmeiov1.FilterDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(filterdeploymentsResource, c.ns, name), &wasmeiov1.FilterDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*wasmeiov1.FilterDeployment), err
}

// List takes label and field selectors, and returns the list of FilterDeployments that match those selectors.
func (c *FakeFilterDeployments) List(opts v1.ListOptions) (result *wasmeiov1.FilterDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(filterdeploymentsResource, filterdeploymentsKind, c.ns, opts), &wasmeiov1.FilterDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &wasmeiov1.FilterDeploymentList{ListMeta: obj.(*wasmeiov1.FilterDeploymentList).ListMeta}
	for _, item := range obj.(*wasmeiov1.FilterDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested filterDeployments.
func (c *FakeFilterDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(filterdeploymentsResource, c.ns, opts))

}

// Create takes the representation of a filterDeployment and creates it.  Returns the server's representation of the filterDeployment, and an error, if there is any.
func (c *FakeFilterDeployments) Create(filterDeployment *wasmeiov1.FilterDeployment) (result *wasmeiov1.FilterDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(filterdeploymentsResource, c.ns, filterDeployment), &wasmeiov1.FilterDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*wasmeiov1.FilterDeployment), err
}

// Update takes the representation of a filterDeployment and updates it. Returns the server's representation of the filterDeployment, and an error, if there is any.
func (c *FakeFilterDeployments) Update(filterDeployment *wasmeiov1.FilterDeployment) (result *wasmeiov1.FilterDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(filterdeploymentsResource, c.ns, filterDeployment), &wasmeiov1.FilterDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*wasmeiov1.FilterDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFilterDeployments) UpdateStatus(filterDeployment *wasmeiov1.FilterDeployment) (*wasmeiov1.FilterDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(filterdeploymentsResource, "status", c.ns, filterDeployment), &wasmeiov1.FilterDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*wasmeiov1.FilterDeployment), err
}

// Delete takes name of the filterDeployment and deletes it. Returns an error if one occurs.
func (c *FakeFilterDeployments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(filterdeploymentsResource, c.ns, name), &wasmeiov1.FilterDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFilterDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(filterdeploymentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &wasmeiov1.FilterDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched filterDeployment.
func (c *FakeFilterDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *wasmeiov1.FilterDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(filterdeploymentsResource, c.ns, name, pt, data, subresources...), &wasmeiov1.FilterDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*wasmeiov1.FilterDeployment), err
}
