// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for wasme.io/v1 resources

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Generated Deepcopy methods for FilterDeployment

func (in *FilterDeployment) DeepCopyInto(out *FilterDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

func (in *FilterDeployment) DeepCopy() *FilterDeployment {
	if in == nil {
		return nil
	}
	out := new(FilterDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *FilterDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FilterDeploymentList) DeepCopyInto(out *FilterDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FilterDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

func (in *FilterDeploymentList) DeepCopy() *FilterDeploymentList {
	if in == nil {
		return nil
	}
	out := new(FilterDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *FilterDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
