
# Rbac manifests for wasme-operator

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wasme-operator
  labels:
    app: wasme-operator
rules:
- apiGroups:
  - wasme.io
  resources:
  - filterdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wasme.io
  resources:
  - filterdeployments/status
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wasme-operator
  labels:
    app: wasme-operator
subjects:
- kind: ServiceAccount
  name: wasme-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: wasme-operator
  apiGroup: rbac.authorization.k8s.io