apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ""
    app.kubernetes.io/name: ""
  name: filterdeployments.wasme.io
spec:
  group: wasme.io
  names:
    kind: FilterDeployment
    listKind: FilterDeploymentList
    plural: filterdeployments
    singular: filterdeployment
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
