// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModuleSpec struct {
	// The name of the extension. Must be unique within a repository.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Module logo URL. optional
	LogoUrl string `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	// Short description of the extension.
	ShortDescription string `protobuf:"bytes,3,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	// Long description of the extension.
	// TODO support colocated markdown file OR link to markdown file
	LongDescription string `protobuf:"bytes,4,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	// URL for the module in Solo.io's repository.
	ModuleUrl string `protobuf:"bytes,5,opt,name=module_url,json=moduleUrl,proto3" json:"module_url,omitempty"`
	// Link to documentation for the extension.
	DocumentationUrl string `protobuf:"bytes,6,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	// Link to repository containing the extension's source code.
	RepositoryUrl string `protobuf:"bytes,7,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	// The name of the entity that authored the extension.
	CreatorName string `protobuf:"bytes,8,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	// Link to the entity that authored the extension.
	CreatorUrl string `protobuf:"bytes,9,opt,name=creator_url,json=creatorUrl,proto3" json:"creator_url,omitempty"`
	// List of version-specific extension information.
	Versions []*VersionedModuleSpec `protobuf:"bytes,10,rep,name=versions,proto3" json:"versions,omitempty"`
	// List of tags describing extension.
	Tags                 []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleSpec) Reset()         { *m = ModuleSpec{} }
func (m *ModuleSpec) String() string { return proto.CompactTextString(m) }
func (*ModuleSpec) ProtoMessage()    {}
func (*ModuleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *ModuleSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleSpec.Unmarshal(m, b)
}
func (m *ModuleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleSpec.Marshal(b, m, deterministic)
}
func (m *ModuleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleSpec.Merge(m, src)
}
func (m *ModuleSpec) XXX_Size() int {
	return xxx_messageInfo_ModuleSpec.Size(m)
}
func (m *ModuleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleSpec proto.InternalMessageInfo

func (m *ModuleSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleSpec) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *ModuleSpec) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *ModuleSpec) GetLongDescription() string {
	if m != nil {
		return m.LongDescription
	}
	return ""
}

func (m *ModuleSpec) GetModuleUrl() string {
	if m != nil {
		return m.ModuleUrl
	}
	return ""
}

func (m *ModuleSpec) GetDocumentationUrl() string {
	if m != nil {
		return m.DocumentationUrl
	}
	return ""
}

func (m *ModuleSpec) GetRepositoryUrl() string {
	if m != nil {
		return m.RepositoryUrl
	}
	return ""
}

func (m *ModuleSpec) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *ModuleSpec) GetCreatorUrl() string {
	if m != nil {
		return m.CreatorUrl
	}
	return ""
}

func (m *ModuleSpec) GetVersions() []*VersionedModuleSpec {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *ModuleSpec) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type VersionedModuleSpec struct {
	// Module version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Compatible envoy version (TODO semver / version constraint syntax?)
	EnvoyVersion string `protobuf:"bytes,2,opt,name=envoy_version,json=envoyVersion,proto3" json:"envoy_version,omitempty"`
	// Instructions for install on various Envoy platforms
	// This does NOT need to be provided by the module author
	InstallInstructions  *InstallInstructions `protobuf:"bytes,3,opt,name=install_instructions,json=installInstructions,proto3" json:"install_instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VersionedModuleSpec) Reset()         { *m = VersionedModuleSpec{} }
func (m *VersionedModuleSpec) String() string { return proto.CompactTextString(m) }
func (*VersionedModuleSpec) ProtoMessage()    {}
func (*VersionedModuleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *VersionedModuleSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedModuleSpec.Unmarshal(m, b)
}
func (m *VersionedModuleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedModuleSpec.Marshal(b, m, deterministic)
}
func (m *VersionedModuleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedModuleSpec.Merge(m, src)
}
func (m *VersionedModuleSpec) XXX_Size() int {
	return xxx_messageInfo_VersionedModuleSpec.Size(m)
}
func (m *VersionedModuleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedModuleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedModuleSpec proto.InternalMessageInfo

func (m *VersionedModuleSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionedModuleSpec) GetEnvoyVersion() string {
	if m != nil {
		return m.EnvoyVersion
	}
	return ""
}

func (m *VersionedModuleSpec) GetInstallInstructions() *InstallInstructions {
	if m != nil {
		return m.InstallInstructions
	}
	return nil
}

// Set of install instructions for each supported envoy flavor
type InstallInstructions struct {
	Gloo                 *InstallInstructions_Gloo         `protobuf:"bytes,1,opt,name=gloo,proto3" json:"gloo,omitempty"`
	VanillaEnvoy         *InstallInstructions_VanillaEnvoy `protobuf:"bytes,3,opt,name=vanilla_envoy,json=vanillaEnvoy,proto3" json:"vanilla_envoy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *InstallInstructions) Reset()         { *m = InstallInstructions{} }
func (m *InstallInstructions) String() string { return proto.CompactTextString(m) }
func (*InstallInstructions) ProtoMessage()    {}
func (*InstallInstructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *InstallInstructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallInstructions.Unmarshal(m, b)
}
func (m *InstallInstructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallInstructions.Marshal(b, m, deterministic)
}
func (m *InstallInstructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallInstructions.Merge(m, src)
}
func (m *InstallInstructions) XXX_Size() int {
	return xxx_messageInfo_InstallInstructions.Size(m)
}
func (m *InstallInstructions) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallInstructions.DiscardUnknown(m)
}

var xxx_messageInfo_InstallInstructions proto.InternalMessageInfo

func (m *InstallInstructions) GetGloo() *InstallInstructions_Gloo {
	if m != nil {
		return m.Gloo
	}
	return nil
}

func (m *InstallInstructions) GetVanillaEnvoy() *InstallInstructions_VanillaEnvoy {
	if m != nil {
		return m.VanillaEnvoy
	}
	return nil
}

type InstallInstructions_Gloo struct {
	Glooctl              string   `protobuf:"bytes,1,opt,name=glooctl,proto3" json:"glooctl,omitempty"`
	GatewayYaml          string   `protobuf:"bytes,2,opt,name=gateway_yaml,json=gatewayYaml,proto3" json:"gateway_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallInstructions_Gloo) Reset()         { *m = InstallInstructions_Gloo{} }
func (m *InstallInstructions_Gloo) String() string { return proto.CompactTextString(m) }
func (*InstallInstructions_Gloo) ProtoMessage()    {}
func (*InstallInstructions_Gloo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2, 0}
}

func (m *InstallInstructions_Gloo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallInstructions_Gloo.Unmarshal(m, b)
}
func (m *InstallInstructions_Gloo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallInstructions_Gloo.Marshal(b, m, deterministic)
}
func (m *InstallInstructions_Gloo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallInstructions_Gloo.Merge(m, src)
}
func (m *InstallInstructions_Gloo) XXX_Size() int {
	return xxx_messageInfo_InstallInstructions_Gloo.Size(m)
}
func (m *InstallInstructions_Gloo) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallInstructions_Gloo.DiscardUnknown(m)
}

var xxx_messageInfo_InstallInstructions_Gloo proto.InternalMessageInfo

func (m *InstallInstructions_Gloo) GetGlooctl() string {
	if m != nil {
		return m.Glooctl
	}
	return ""
}

func (m *InstallInstructions_Gloo) GetGatewayYaml() string {
	if m != nil {
		return m.GatewayYaml
	}
	return ""
}

type InstallInstructions_VanillaEnvoy struct {
	Config               string   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallInstructions_VanillaEnvoy) Reset()         { *m = InstallInstructions_VanillaEnvoy{} }
func (m *InstallInstructions_VanillaEnvoy) String() string { return proto.CompactTextString(m) }
func (*InstallInstructions_VanillaEnvoy) ProtoMessage()    {}
func (*InstallInstructions_VanillaEnvoy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2, 1}
}

func (m *InstallInstructions_VanillaEnvoy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallInstructions_VanillaEnvoy.Unmarshal(m, b)
}
func (m *InstallInstructions_VanillaEnvoy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallInstructions_VanillaEnvoy.Marshal(b, m, deterministic)
}
func (m *InstallInstructions_VanillaEnvoy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallInstructions_VanillaEnvoy.Merge(m, src)
}
func (m *InstallInstructions_VanillaEnvoy) XXX_Size() int {
	return xxx_messageInfo_InstallInstructions_VanillaEnvoy.Size(m)
}
func (m *InstallInstructions_VanillaEnvoy) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallInstructions_VanillaEnvoy.DiscardUnknown(m)
}

var xxx_messageInfo_InstallInstructions_VanillaEnvoy proto.InternalMessageInfo

func (m *InstallInstructions_VanillaEnvoy) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func init() {
	proto.RegisterType((*ModuleSpec)(nil), "ModuleSpec")
	proto.RegisterType((*VersionedModuleSpec)(nil), "VersionedModuleSpec")
	proto.RegisterType((*InstallInstructions)(nil), "InstallInstructions")
	proto.RegisterType((*InstallInstructions_Gloo)(nil), "InstallInstructions.Gloo")
	proto.RegisterType((*InstallInstructions_VanillaEnvoy)(nil), "InstallInstructions.VanillaEnvoy")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x55, 0x5a, 0xfa, 0x31, 0x69, 0x61, 0x71, 0x57, 0x28, 0xbb, 0x12, 0xa2, 0x5b, 0x04,
	0x5a, 0x84, 0xa8, 0xd0, 0xf2, 0x06, 0x7c, 0xad, 0xf6, 0x00, 0x87, 0x20, 0x56, 0x82, 0x4b, 0x64,
	0x5c, 0x13, 0x2c, 0x39, 0x9e, 0xca, 0x71, 0x8b, 0xfa, 0x16, 0xbc, 0x00, 0x0f, 0xca, 0x0d, 0xcd,
	0xc4, 0xa1, 0x59, 0x6d, 0x4e, 0xf1, 0xfc, 0xe7, 0xe7, 0x99, 0xd1, 0x7f, 0x62, 0x98, 0x29, 0x19,
	0xa4, 0xc5, 0x62, 0xb5, 0xf1, 0x18, 0x70, 0xf9, 0xbb, 0x0f, 0xf0, 0x11, 0xd7, 0x5b, 0xab, 0x3f,
	0x6f, 0xb4, 0x12, 0x02, 0x06, 0x4e, 0x96, 0x3a, 0xed, 0x2d, 0x7a, 0xe7, 0x93, 0x8c, 0xcf, 0xe2,
	0x04, 0xc6, 0x16, 0x0b, 0xcc, 0xb7, 0xde, 0xa6, 0x77, 0x58, 0x1f, 0x51, 0xfc, 0xc5, 0x5b, 0xf1,
	0x02, 0x1e, 0x54, 0x3f, 0xd1, 0x87, 0x7c, 0xad, 0x2b, 0xe5, 0xcd, 0x26, 0x18, 0x74, 0x69, 0x9f,
	0x99, 0x23, 0x4e, 0xbc, 0x3b, 0xe8, 0xe2, 0x39, 0x1c, 0x59, 0x74, 0xc5, 0x0d, 0x76, 0xc0, 0xec,
	0x7d, 0xd2, 0xdb, 0xe8, 0x23, 0x80, 0x92, 0x87, 0xe2, 0xa6, 0x77, 0x19, 0x9a, 0xd4, 0x4a, 0x6c,
	0xbb, 0x46, 0xb5, 0x2d, 0xb5, 0x0b, 0x92, 0x78, 0xa6, 0x86, 0x75, 0xdb, 0x1b, 0x09, 0x82, 0x9f,
	0xc2, 0x3d, 0xaf, 0x37, 0x58, 0x99, 0x80, 0x7e, 0xcf, 0xe4, 0x88, 0xc9, 0xd9, 0x41, 0x25, 0xec,
	0x0c, 0xa6, 0xca, 0x6b, 0x19, 0xd0, 0xe7, 0xec, 0xc0, 0x98, 0xa1, 0x24, 0x6a, 0x9f, 0xc8, 0x88,
	0xc7, 0xd0, 0x84, 0x5c, 0x66, 0xc2, 0x04, 0x44, 0x89, 0x6a, 0xbc, 0x82, 0xf1, 0x4e, 0xfb, 0xca,
	0xa0, 0xab, 0x52, 0x58, 0xf4, 0xcf, 0x93, 0x8b, 0xe3, 0xd5, 0x75, 0x2d, 0xe8, 0xf5, 0xc1, 0xe5,
	0xec, 0x3f, 0x45, 0x7e, 0x07, 0x59, 0x54, 0x69, 0xb2, 0xe8, 0x93, 0xdf, 0x74, 0x5e, 0xfe, 0xe9,
	0xc1, 0xbc, 0xe3, 0x96, 0x48, 0x61, 0x14, 0xef, 0xc5, 0xf5, 0x34, 0xa1, 0x78, 0x02, 0x33, 0xed,
	0x76, 0xb8, 0xcf, 0x9b, 0x7c, 0xbd, 0xa6, 0x29, 0x8b, 0xb1, 0x94, 0xb8, 0x84, 0x63, 0xe3, 0xaa,
	0x20, 0xad, 0xcd, 0xe9, 0xeb, 0xb7, 0x2a, 0xf0, 0xa0, 0xb4, 0x2e, 0x1a, 0xf4, 0xaa, 0x4e, 0x5e,
	0xb5, 0x72, 0xd9, 0xdc, 0xdc, 0x16, 0x97, 0x7f, 0x7b, 0x30, 0xef, 0x80, 0xc5, 0x4b, 0x18, 0x14,
	0x16, 0x91, 0x87, 0x4b, 0x2e, 0x4e, 0xba, 0x0a, 0xae, 0x2e, 0x2d, 0x62, 0xc6, 0x98, 0xf8, 0x00,
	0xb3, 0x9d, 0x74, 0xc6, 0x5a, 0x99, 0xf3, 0x9c, 0x71, 0x90, 0xb3, 0xce, 0x7b, 0xd7, 0x35, 0xf9,
	0x9e, 0xc0, 0x6c, 0xba, 0x6b, 0x45, 0xa7, 0x6f, 0x61, 0x40, 0x55, 0xc9, 0x1e, 0xaa, 0xab, 0x82,
	0x6d, 0xec, 0x89, 0x21, 0xad, 0xb6, 0x90, 0x41, 0xff, 0x92, 0xfb, 0x7c, 0x2f, 0xcb, 0xe6, 0x27,
	0x4e, 0xa2, 0xf6, 0x55, 0x96, 0xf6, 0xf4, 0x19, 0x4c, 0xdb, 0x2d, 0xc4, 0x43, 0x18, 0x2a, 0x74,
	0x3f, 0x4c, 0x11, 0x6b, 0xc5, 0xe8, 0xcd, 0xe4, 0xdb, 0x28, 0xbe, 0x9f, 0xef, 0x43, 0x7e, 0x40,
	0xaf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x98, 0xd7, 0x0f, 0xfc, 0x51, 0x03, 0x00, 0x00,
}
