// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	v1 "github.com/solo-io/wasme/pkg/operator/api/wasme.io/v1"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// ApplyFilter provides a mock function with given fields: filter
func (_m *Provider) ApplyFilter(filter *v1.FilterSpec) error {
	ret := _m.Called(filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.FilterSpec) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFilter provides a mock function with given fields: filter
func (_m *Provider) RemoveFilter(filter *v1.FilterSpec) error {
	ret := _m.Called(filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.FilterSpec) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
