// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package config

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	RootIds              []string `protobuf:"bytes,1,rep,name=root_ids,json=rootIds,proto3" json:"root_ids,omitempty"`
	AbiVersion           string   `protobuf:"bytes,2,opt,name=abi_version,json=abiVersion,proto3" json:"abi_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetRootIds() []string {
	if m != nil {
		return m.RootIds
	}
	return nil
}

func (m *Config) GetAbiVersion() string {
	if m != nil {
		return m.AbiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "solo.extendenvoy.config.Config")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2f, 0xce, 0xcf, 0xc9, 0xd7, 0x4b,
	0xad, 0x28, 0x49, 0xcd, 0x4b, 0x49, 0xcd, 0x2b, 0xcb, 0xaf, 0xd4, 0x83, 0x48, 0x2b, 0xb9, 0x70,
	0xb1, 0x39, 0x83, 0x59, 0x42, 0x92, 0x5c, 0x1c, 0x45, 0xf9, 0xf9, 0x25, 0xf1, 0x99, 0x29, 0xc5,
	0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0xec, 0x20, 0xbe, 0x67, 0x4a, 0xb1, 0x90, 0x3c, 0x17,
	0x77, 0x62, 0x52, 0x66, 0x7c, 0x59, 0x6a, 0x51, 0x71, 0x66, 0x7e, 0x9e, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x57, 0x62, 0x52, 0x66, 0x18, 0x44, 0xc4, 0x89, 0x23, 0x8a, 0x0d, 0x62, 0x5e,
	0x12, 0x1b, 0xd8, 0x3e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xf7, 0x21, 0x95, 0x7f,
	0x00, 0x00, 0x00,
}
