name: pull_request

on:
  pull_request: {}

jobs:
  test:
    name: hello-world
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
